server:
  port: 9292


spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: en1-group1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.kafka.example.dto




#        spring.json.trusted.packages: java.util, java.lang, com.kafka.producer.dto
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.kafka.example.dto




#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: jt-group-demo-1