server:
  port: 9292


spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jt-group-demo-6
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.kafka.consumer.dto




#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: jt-group-demo-1