server:
  port: 9292
#
#
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: jt-group-3
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.add.type.headers: false




#        spring.json.trusted.packages: java.util, java.lang, com.kafka.producer.dto
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.kafka.consumer.dto.CustomerDto




#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: jt-group-demo-1